### ISSUE TITLE
Link to paper

### ISSUE THREAD

**Issue by ofirkris** [zhuoinoulu/pidinet#1]
Hello, can you add a link to the published paper?
When are you planning to release code and weights?

**Comment by zhuoinoulu** [comment]
> Hello, can you add a link to the published paper?
> When are you planning to release code and weights?

Hi. Sure, now I am preparing for the paper and the code. Possibly in one or two weeks.

**Comment by 2916850681** [comment]
hello,is the paper availiable? I am interested but can't find it on the Internet

**Comment by 2916850681** [comment]
Is paper availiable now？

**Comment by zzzzzz0407** [comment]
Hello, the paper has been released and when the code will be released?

**Comment by zhuoinoulu** [comment]
@zzzzzz0407  Hello, the code is now released.
