### ISSUE TITLE
提供的checkpoint加载问题，不能测试图片？

### ISSUE THREAD

**Issue by mucle** [zhuoinoulu/pidinet#10]
![2](https://user-images.githubusercontent.com/34679219/132979521-3c553926-9f3f-4c9a-b431-7c58eb0f848a.png)
![3(1)](https://user-images.githubusercontent.com/34679219/132979527-b775abc7-fc6d-474d-951e-15b1179c74b7.png)
![1](https://user-images.githubusercontent.com/34679219/132979534-785548b5-e77f-4269-aca8-23f4e1521ba5.png)

**Comment by zhuoinoulu** [comment]
你下载的checkpoint好像被当成了zip文件， 下载后看能不能先随便改个后缀名，然后再在程序里加载？
