### ISSUE TITLE
Multicue dataset

### ISSUE THREAD

**Issue by WCJ1998** [zhuoinoulu/pidinet#11]
Hello, could you provide a link to the Multicue dataset and the enhanced data? thank you very much

**Comment by rrryan2016** [comment]
> Hello, could you provide a link to the Multicue dataset and the enhanced data? thank you very much

1. Link of Multicue: https://serre-lab.clps.brown.edu/resource/multicue/
2. You can take a reference to https://github.com/yun-liu/RCF/issues/124 for the data augmentation.

**Comment by WCJ1998** [comment]
Hello, the downloaded Multicue dataset is all pictures. How do you use it when testing the ODS target value? Because the labels on the BSDS dataset are in mat format, can you tell me how the multicue dataset is tested? thank you very much!

**Comment by rrryan2016** [comment]
Transfer the png files to mat files. 

Take the MATLAB codes below for reference:

```
main_path =  'C:\Personal\data\multicue_groundtruth\combine\edge_input'; 
output_main_path =  'C:\Personal\data\multicue_groundtruth\combine\edge_output'; 
image_names = {'4580_left_0165',  '4680_left_0170', '4176_left_0273',  '4486_left_0036', '4163_left_0052',  '4491_left_0070', '4582_left_0020',  '4673_left_0115', '4108_left_0948',  '4588_left_0200', '4179_left_0315',  '4676_left_0093', '4569_left_0060',  '4175_left_0184', '4592_left_0020',  '4571_left_0062', '4108_left_2343',  '4457_left_0050', '4187_left_0071',  '4113_left_2396', '4171_left_0221',  '4492_left_0090', '4383_left_0010',  '4596_left_0020', '4378_left_0011',  '4406_left_0030', '4568_left_0020',  '4178_left_0052', '4186_left_0127',  '4494_left_0070', '4386_left_0020',  '4586_left_0080', '4523_left_0070',  '4396_left_0050', '4108_left_0082',  '4689_left_0050', '4184_left_0048',  '4209_left_0034', '4453_left_0020',  '4640_left_0080', '4665_left_0040',  '4524_left_0040', '4558_left_0260',  '4097_left_0667', '4668_left_0130',  '4188_left_0315', '4177_left_0071',  '4200_left_0221', '4687_left_0130',  '4548_left_0080', '4108_left_0446',  '4470_left_0010', '4404_left_0010',  '4663_left_0010', '4625_left_0140',  '4504_left_0025', '4449_left_0290',  '4475_left_0010', '4113_left_0082',  '4407_left_0100', '4567_left_0030',  '4420_left_0040', '4603_left_0050',  '4385_left_0020', '4398_left_0100',  '4380_left_0025', '4669_left_0080',  '4402_left_0040', '4403_left_0010',  '4451_left_0020', '4597_left_0010',  '4210_left_0296', '4172_left_0067',  '4114_left_0611', '4674_left_0100',  '4484_left_0040', '4483_left_0170',  '4552_left_0080', '4561_left_0100',  '4605_left_0220', '4190_left_0161',  '4101_left_0382',  '4609_left_0080', '4684_left_0010',  '4710_left_0035', '4220_left_0221',  '4409_left_0020', '4629_left_0050',  '4382_left_0015', '4638_left_0070',  '4685_left_0045', '4208_left_0052',  '4452_left_0010', '4192_left_0221',  '4377_left_0016', '4564_left_0010',  '4198_left_0034', '4100_left_2268',  '4644_left_0120', '4641_left_0030'};
for image=image_names
sprintf('processing %s ...',char(image))
for i=1:6 
    b =  imread(fullfile(main_path,sprintf('%s.%d.png',char(image),i)));
    b = logical(b);
    groundTruth{i}.Boundaries = b;
     save(fullfile(output_main_path,sprintf('%s.mat',char(image))),'groundTruth');
end
end
```

**Comment by WCJ1998** [comment]
I'm sorry to bother you again. I was using matlab to test the results of the multicue data set and found that it took more than ten hours to test an epoch on my computer, but it was not completed. I would like to ask if you have encountered this kind of problem. I still need to do other operations during the test. Thank you very much.

**Comment by rrryan2016** [comment]
Same problem in experiments. Simply because the resolution of Multicue (1280 by 720 pixels) is much larger than NYUD or BSDS500.  

I found an evaluation code by Python (https://github.com/Walstruzz/edge_eval_python) but has not been verified yet.  You can have a try if it can be more cost-efficient.

**Comment by WCJ1998** [comment]
thank you very much. This code is available, and it is significantly faster on my server. The result is the same as using matlab, but the code should only run on the cpu of the linux system, and the speed may depend on the cpu performance of the server.

**Comment by rrryan2016** [comment]
Bravo! Thanks for this kind sharing.

**Comment by zhuoinoulu** [comment]
@WCJ1998 @rrryan2016 the dataset can be downloaded at https://drive.google.com/file/d/1-tyt_KyzlYc9APafdh5mHJzh2K_F2hM8/view?usp=sharing

**Comment by XRONHH** [comment]
I'm sorry to bother you,  i can't download your mutilcue dataset link https://github.com/zhuoinoulu/pidinet/issues/11#issuecomment-987661561 ,due to network reasons. Could you give me a domestic link?this is my e-mail:529948572@qq.com
