### ISSUE TITLE
weights_c

### ISSUE THREAD

**Issue by RuosiZhou** [zhuoinoulu/pidinet#14]
Hello, your work is perfect, but I took a look at the CPDC program you wrote today. I don't quite understand the solution of weights_c. Did something go wrong?

**Comment by zhuoinoulu** [comment]
And in Eq. (7) (see our arxiv paper), 
![image](https://user-images.githubusercontent.com/87975270/138353962-7702d501-8d98-4b8b-b3c0-adf1ed2da3d1.png)
the first part of this equation (w1x1+w2x2+...+w9x9) can be regarded as a 3x3 convolution, and the second part for x5 is a 1x1 convolution. This is how cpdc implements in our code during training.
