### ISSUE TITLE
请问如何多卡运行？

### ISSUE THREAD

**Issue by HAN-BABAY** [zhuoinoulu/pidinet#18]

**Comment by zhuoinoulu** [comment]
你好，这个需要修改main.py，目前我们还没有具体实现。多卡运行应该需要输入图片size一致(这样可以使得batch size > 1从而均分给多个GPU). 所以实现方案可以是先对输入做一个预处理，使得size一致，然后可以调用[DistributedDataParallel](https://pytorch.org/docs/stable/notes/cuda.html#cuda-nn-ddp-instead)完成多GPU运行。

当然并不排除size不一致也能多卡运行的可能  ఠ_ఠ，这种情况可能再需要调研一下~

**Comment by HAN-BABAY** [comment]
谢谢
