### ISSUE TITLE
Is paper availiable now?

### ISSUE THREAD

**Issue by 2916850681** [zhuoinoulu/pidinet#2]

**Comment by zhuoinoulu** [comment]
Hi, sorry for the late response. I have now uploaded the paper to [https://arxiv.org/abs/2108.07009](https://arxiv.org/abs/2108.07009).

**Comment by 2916850681** [comment]
> Hi, sorry for the late response. I have now uploaded the paper to https://arxiv.org/abs/2108.07009.

thx
