### ISSUE TITLE
關於table2的訓練

### ISSUE THREAD

**Issue by nancy971323** [zhuoinoulu/pidinet#20]
以下是我訓練table2的參數
但是ods, ois與論文不同
請問是該修改哪裡呢
python main.py --model pidinet --config carv4 --sa --dil --resume --iter-size 24 -j 4 --gpu 0 --epochs 14 --lr 0.005 --lr-type multistep --lr-steps 8-12 --wd 1e-1 --savedir mysave --datadir data/BSDS500/HED-BSDS --dataset BSDS --only-bsds
ODS=0.761, OIS=0.775

**Comment by zhuoinoulu** [comment]
> 以下是我訓練table2的參數 但是ods, ois與論文不同 請問是該修改哪裡呢 python main.py --model pidinet --config carv4 --sa --dil --resume --iter-size 24 -j 4 --gpu 0 --epochs 14 --lr 0.005 --lr-type multistep --lr-steps 8-12 --wd 1e-1 --savedir mysave --datadir data/BSDS500/HED-BSDS --dataset BSDS --only-bsds ODS=0.761, OIS=0.775

你好，table2 training用到了BSDS的training set(200 images) + VOC, testing用到的是BSDS validation set (100 images)，正确的训练命令应该是:
python main.py --model pidinet --config carv4 --sa --dil --resume --iter-size 24 -j 4 --gpu 0 --datadir /path/to/BSDS500 --dataset BSDS --epochs 20 --lr 0.005 --lr-type multistep --lr-steps 10-16 --wd 1e-4 --savedir mysave --ablation
