### ISSUE TITLE
bsds_pascal_train_pair_train.lst和bsds_pascal_train_pair_val.lst？

### ISSUE THREAD

**Issue by HAN-BABAY** [zhuoinoulu/pidinet#22]
作者您好，请问这两个LST文件是什么作用那？这两个里面的BSDS500数据被扩大了48倍，但是我看文中的实验用的都是96倍的lst（bsds_pascal_train200_pair.lst和bsds_pascal_train_pair.lst）。

**Comment by zhuoinoulu** [comment]
lst也是扩大了96倍的，比如bsds_pascal_train_pair.lst里边bsds一共有28800行，对应28800=300*96.

**Comment by HAN-BABAY** [comment]
嗯嗯，刚刚是我没有问清楚，我想问的是bsds_pascal_train_pair_train.lst和bsds_pascal_train_pair_val.lst里面BSDS一共有14400行，这两个lst文件是什么作用那？

**Comment by zhuoinoulu** [comment]
这两个文件应该没有用...

**Comment by HAN-BABAY** [comment]
十分感谢

**Comment by HAN-BABAY** [comment]
十分感谢

**Comment by ToBeNormal** [comment]
@zhuoinoulu 您好，我想请教下你有数据集扩充96倍处理流程的代码吗？以及您有BSDS500原始的有4-9个label的版本，我在官网上下载下来的只有最终融合后的label。
![image](https://user-images.githubusercontent.com/79554332/144748134-cb749f9e-a6fd-451a-97ff-416f3d1ead61.png)

**Comment by zhuoinoulu** [comment]
> @zhuoinoulu 您好，我想请教下你有数据集扩充96倍处理流程的代码吗？以及您有BSDS500原始的有4-9个label的版本，我在官网上下载下来的只有最终融合后的label。 ![image](https://user-images.githubusercontent.com/79554332/144748134-cb749f9e-a6fd-451a-97ff-416f3d1ead61.png)

你好，数据的扩充处理具体可以问问wenzhe @rrryan2016 . 简单来说，从 http://mftp.mmcheng.net/liuyun/rcf/data/HED-BSDS.tar.gz 和 http://mftp.mmcheng.net/liuyun/rcf/data/PASCAL.tar.gz 下载下来的数据已经是扩充好的数据了，可以在此基础上用opencv加一些额外的scale操作. 我们并没有下载原始的版本。

**Comment by ToBeNormal** [comment]
@zhuoinoulu 好的，感谢您的回答。

**Comment by ToBeNormal** [comment]
@rrryan2016 您好，想请问下原始下载下来的数据集里面的图片各点像素值和扩充后的不太一致，论文里面只提到了旋转、裁剪、缩放和翻转这些预处理操作，请问是额外有什么亮度的预处理吗？

**Comment by rrryan2016** [comment]
> @rrryan2016 您好，想请问下原始下载下来的数据集里面的图片各点像素值和扩充后的不太一致，论文里面只提到了旋转、裁剪、缩放和翻转这些预处理操作，请问是额外有什么亮度的预处理吗？

并没有做亮度上的预处理。

您所提到的“原始下载下来的数据集里面的图片各点像素值和扩充后的不太一致”会不会是就是空间上变换后，同一坐标的像素本应就改变？

或者“不一致”具体是如何展现的呢？是否存在规律还是随机的？

**Comment by ToBeNormal** [comment]
@rrryan2016 您好，感谢您的回复，我肉眼上看起来是随机的。如下图，为我从官网上下载下来的8049.jpg
![image](https://user-images.githubusercontent.com/79554332/148028559-0f1a3158-7931-4ff9-a384-3cd002c4eee3.png)
下面的图为从您提供的数据集里面的aug_data/0.0_1.0,我肉眼上比较这两个图片的亮度不一样，一样的区域的像素点数值也进行了比较是不一样的
![image](https://user-images.githubusercontent.com/79554332/148028769-d30a5c2a-16bc-437f-929d-03d09e010bae.png)
aug_data/0.0_1.0与原数据集相比按论文所说是只做了宽度为63和长度为63的左边和上边填充，我把原始的未填充区域扣取出来了比较像素值。
另外，您的填充好像也是随机的，crop我也没能跟您保持一致，请问您方便提供从官网下载的数据集https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html#bsds500到您提供的数据集HED-BSDS的处理代码吗？这个问题困扰我很久了，期待您的回复！！

**Comment by ToBeNormal** [comment]
@rrryan2016 您好，我现在的进展是使用了torch里的库进行旋转，可以保持图像清晰度，但是在进行1.5倍图像scale的时候模糊很多，方便问下您是使用什么方法sclae的嘛？我用的cv2.resize和transforms.Resize这些都不太行
