### ISSUE TITLE
运行命令行出错，可以帮忙看一下这是哪里出错了吗

### ISSUE THREAD

**Issue by dongliuqingqing** [zhuoinoulu/pidinet#24]
python main.py --model pidinet --config carv4 --sa --dil --resume --iter-size 24 -j 0 --gpu 0 --epochs 20 --lr 0.005 --lr-type multistep --lr-steps 10-16 --wd 1e-4 --savedir /path/to/table5_pidinet --datadir path/to/BSDS500 --dataset BSDS
会出现错误 No such file or directory: 'path/to/BSDS500\\PASCAL/aug_gt/0.0_0/2009_003007.png'
麻烦请教一下可以帮忙看看这是哪里出错了吗

**Comment by zhuoinoulu** [comment]
需要修改 "path/to/BSDS500" 成存储图片的路径, "/path/to/table5_pidinet"也可能需要修改

**Comment by dongliuqingqing** [comment]
> 需要修改 "path/to/BSDS500" 成存储图片的路径, "/path/to/table5_pidinet"也可能需要修改

好的，非常感谢，我试试。
