### ISSUE TITLE
关于PiDinet推理时候的FPS问题

### ISSUE THREAD

**Issue by cimerainbow** [zhuoinoulu/pidinet#37]
我这边运行您提供的计算FPS的程序代码遇到了一些问题。在BSDS500数据集上计算出来的FPS是要慢于您论文提到的数据。我的在同样的GPU条件下HED的推理速度是要快于PiDinet的，您能不能提供一下您测试用的HED代码。

**Comment by zhuoinoulu** [comment]
@cimerainbow 你好,我更新了hed的测试代码,在2080Ti上跑出来是75~78FPS.请参考
https://github.com/zhuoinoulu/pidinet/blob/36f6506df68e46260d4424446ceb9da3aa267598/models/hed_fps.py#L5

**Comment by cimerainbow** [comment]
谢谢您的技术支持
