### ISSUE TITLE
About edge detection fps

### ISSUE THREAD

**Issue by KengDong** [zhuoinoulu/pidinet#9]
When I use python main.py --model pidinet_tiny to generate the edge images of my data set, the average edge extraction of each image can only reach about 90ms, and when using python main.py --model pidinet_tiny, it is displayed as: Threshold for ground truth: 76.800000 on BSDS_VOC, fps: 148.358999. I would like to ask what ways can be used to improve the speed of python main.py --model pidinet_tiny edge detection, such as not generating jpg and mat files?

**Comment by KengDong** [comment]
Running test [2512/2521]
Running test [2513/2521]
Running test [2514/2521]
Running test [2515/2521]
Running test [2516/2521]
Running test [2517/2521]
Running test [2518/2521]
Running test [2519/2521]
Running test [2520/2521]
Running test [2521/2521]
##########Time########## 2021-09-11 21:18:20

These pictures took 200 seconds to complete the edge detection

**Comment by emmmmmmmer** [comment]
Hello, in the test of my laptop 3060 graphics card, I performed boundary detection on my own pictures and found that the graphics card can only run at 20%. Is there any way to make my graphics card fully used to increase the speed?

**Comment by zhuoinoulu** [comment]
> When I use python main.py --model pidinet_tiny to generate the edge images of my data set, the average edge extraction of each image can only reach about 90ms, and when using python main.py --model pidinet_tiny, it is displayed as: Threshold for ground truth: 76.800000 on BSDS_VOC, fps: 148.358999. I would like to ask what ways can be used to improve the speed of python main.py --model pidinet_tiny edge detection, such as not generating jpg and mat files?

Hi, the speed depends on the image resolutions. In our test, we didn't generate jpg and mat files when testing FPS, sometimes the generating process of jpg and mat files takes even longer than the algorithm. 
The algorithm can be faster using the converted model.

**Comment by zhuoinoulu** [comment]
> Hello, in the test of my laptop 3060 graphics card, I performed boundary detection on my own pictures and found that the graphics card can only run at 20%. Is there any way to make my graphics card fully used to increase the speed?

Perhaps increasing the number of cpu workers in the dataloader help?
